# Generated by Django 2.2.4 on 2019-09-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('fields', models.CharField(max_length=19)),
                ('numbers', models.CharField(max_length=18)),
                ('villagesX', models.CharField(max_length=27)),
                ('villagesY', models.CharField(max_length=27)),
            ],
        ),
    ]
