# Generated by Django 2.2.4 on 2019-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='fields',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='room',
            name='numbers',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='room',
            name='villagesX',
            field=models.CharField(max_length=54),
        ),
        migrations.AlterField(
            model_name='room',
            name='villagesY',
            field=models.CharField(max_length=54),
        ),
    ]
