# Generated by Django 2.2.4 on 2019-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190903_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='villagesX',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='villagesY',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
