# Generated by Django 2.2.4 on 2019-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190903_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='villagesX',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='villagesY',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
