# Generated by Django 2.2.4 on 2019-09-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190903_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
