# Generated by Django 2.2.4 on 2019-09-21 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0007_playerhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blue_brick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_cities',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_cities_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_cities_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_roads',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_roads_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_roads_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_villages',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_villages_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_villages_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_wheat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='blue_wool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='green_brick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='green_cities',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='green_cities_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='green_cities_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='green_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='green_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='green_roads',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='room',
            name='green_roads_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='green_roads_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='green_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='green_villages',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='green_villages_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='green_villages_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='green_wheat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='green_wool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='red_brick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='red_cities',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='red_cities_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='red_cities_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='red_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='red_roads',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='room',
            name='red_roads_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='red_roads_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='red_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='red_villages',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='red_villages_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='red_villages_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='red_wheat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='red_wool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='white_brick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='white_cities',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='white_cities_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='white_cities_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='white_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='white_roads',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='room',
            name='white_roads_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='white_roads_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='white_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='white_villages',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='white_villages_placed_x',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='white_villages_placed_y',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='white_wheat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='white_wool',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PlayerHand',
        ),
    ]
