# Generated by Django 2.2.4 on 2019-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190922_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='villagesX',
        ),
        migrations.RemoveField(
            model_name='room',
            name='villagesY',
        ),
        migrations.AddField(
            model_name='room',
            name='thief_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='thief_y',
            field=models.IntegerField(default=0),
        ),
    ]
