# Generated by Django 2.2.4 on 2019-10-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20191024_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turn',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
